#!/usr/bin/env python3
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import shutil
import sys
import tempfile
import time
from typing import Any

import yaml

VERSION = "0.1.0"
SOURCE_SKILL_REL = "02_operations/source_recognition/SKILL.md"
SOURCE_SKILL_BLOB = "4dc1cd80fc8253c0100788135807f5f6b5865187"
CANDIDATE_ROLE_PREFIX = "source_candidate"
SUPPORTED_SUFFIXES = {".pdb", ".cif", ".mmcif"}


class ToolError(RuntimeError):
    pass


def git_blob_sha(data: bytes) -> str:
    header = f"blob {len(data)}\0".encode("utf-8")
    return hashlib.sha1(header + data).hexdigest()


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def utc_mtime(path: Path) -> str:
    return datetime.fromtimestamp(path.stat().st_mtime, timezone.utc).isoformat()


def load_yaml(path: Path) -> dict[str, Any]:
    if not path.is_file() or path.is_symlink():
        raise ToolError(f"task must be a regular file: {path}")
    try:
        obj = yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise ToolError(f"cannot parse task YAML: {exc}") from exc
    if not isinstance(obj, dict):
        raise ToolError("task root must be a mapping")
    return obj


def skill_root() -> Path:
    return Path(__file__).resolve().parents[2]


def check_semantic_source() -> None:
    path = skill_root() / SOURCE_SKILL_REL
    if not path.is_file() or path.is_symlink():
        raise ToolError(f"source recognition Skill is missing: {path}")
    actual = git_blob_sha(path.read_bytes())
    if actual != SOURCE_SKILL_BLOB:
        raise ToolError(f"SOURCE_SKILL_GUARD_MISMATCH: expected {SOURCE_SKILL_BLOB}, got {actual}")


def resolve_project_path(project_root: Path, value: str, label: str) -> Path:
    p = Path(value)
    target = p.resolve(strict=False) if p.is_absolute() else (project_root / p).resolve(strict=False)
    root = project_root.resolve()
    try:
        target.relative_to(root)
    except ValueError as exc:
        raise ToolError(f"{label} escapes project root: {value}") from exc
    return target


def permission_roots(project_root: Path, values: list[str], label: str) -> list[Path]:
    roots: list[Path] = []
    for value in values:
        if not isinstance(value, str) or not value:
            raise ToolError(f"{label} contains an invalid path")
        roots.append(resolve_project_path(project_root, value, label))
    return roots


def is_within(path: Path, roots: list[Path]) -> bool:
    resolved = path.resolve(strict=False)
    for root in roots:
        try:
            resolved.relative_to(root.resolve(strict=False))
            return True
        except ValueError:
            continue
    return False


def ensure_parent_not_symlink(project_root: Path, path: Path) -> None:
    root = project_root.resolve()
    try:
        rel = path.resolve(strict=False).relative_to(root)
    except ValueError as exc:
        raise ToolError(f"path escapes project root: {path}") from exc
    cursor = root
    for part in rel.parts[:-1]:
        cursor = cursor / part
        if cursor.exists() and cursor.is_symlink():
            raise ToolError(f"symlink parent is not allowed: {cursor}")


def file_record(path: Path, project_root: Path, *, role: str, source_task: str | None, state: str = "present_unvalidated") -> dict[str, Any]:
    data = path.read_bytes()
    record: dict[str, Any] = {
        "path": path.resolve().relative_to(project_root.resolve()).as_posix(),
        "state": state,
        "role": role,
        "size_bytes": len(data),
        "modified_at": utc_mtime(path),
        "sha256": sha256_bytes(data),
        "notes": "generated by source_recognition_deterministic",
    }
    if source_task:
        record["source_task"] = source_task
    return record


def inspect_signature(path: Path) -> tuple[bool, str, str]:
    suffix = path.suffix.lower()
    if suffix not in SUPPORTED_SUFFIXES:
        return False, "UNSUPPORTED_EXTENSION", "UNKNOWN"
    try:
        raw = path.read_bytes()
    except Exception:
        return False, "UNREADABLE", "UNKNOWN"
    if not raw:
        return False, "EMPTY_FILE", "UNKNOWN"
    if b"\x00" in raw[:65536]:
        return False, "BINARY_OR_NUL_CONTENT", "UNKNOWN"
    text = raw[:1048576].decode("utf-8", errors="replace")
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if suffix == ".pdb":
        valid = any(line.startswith(("ATOM", "HETATM", "HEADER", "MODEL", "CRYST1", "TITLE", "REMARK")) for line in lines)
        return (valid, "PDB_MARKER_PRESENT" if valid else "PDB_MARKER_MISSING", "PDB_LOCAL")
    has_data = any(line.lower().startswith("data_") for line in lines)
    has_cif_marker = any(line.startswith("_atom_site.") or line.lower() == "loop_" for line in lines)
    valid = has_data and has_cif_marker
    return (valid, "CIF_MARKERS_PRESENT" if valid else "CIF_MARKERS_MISSING", "MMCIF_LOCAL")


def candidate_id(path: Path, sha: str) -> str:
    stem = "".join(ch if ch.isalnum() else "_" for ch in path.stem)[:24].strip("_") or "source"
    return f"cand_{stem}_{sha[:12]}"


def validate_task(task: dict[str, Any], task_path: Path) -> tuple[Path, Path, list[Path], list[Path], list[Path]]:
    if task.get("schema_version") != 2:
        raise ToolError("unsupported task schema_version")
    task_id = task.get("task_id")
    workstream_id = task.get("workstream_id")
    if not isinstance(task_id, str) or not task_id or not isinstance(workstream_id, str) or not workstream_id:
        raise ToolError("task_id/workstream_id missing")
    unit = task.get("task_unit")
    if not isinstance(unit, dict) or unit.get("mode") != "OPERATION":
        raise ToolError("source recognition deterministic backend requires OPERATION task")
    operation = unit.get("operation")
    if not isinstance(operation, dict) or operation.get("skill_name") != "source_recognition":
        raise ToolError("task operation is not source_recognition")
    project_root_value = task.get("project_root")
    if not isinstance(project_root_value, str) or not project_root_value:
        raise ToolError("project_root missing")
    project_root = Path(project_root_value).resolve()
    if not project_root.is_dir():
        raise ToolError(f"project_root is not a directory: {project_root}")
    try:
        task_path.resolve().relative_to(project_root)
    except ValueError:
        raise ToolError("task path must be inside project_root")
    workdir_value = task.get("work_directory")
    if not isinstance(workdir_value, str) or not workdir_value:
        raise ToolError("work_directory missing")
    workdir = resolve_project_path(project_root, workdir_value, "work_directory")
    permissions = task.get("permissions")
    if not isinstance(permissions, dict):
        raise ToolError("task permissions missing")
    read_roots = permission_roots(project_root, permissions.get("allowed_read_paths", []), "allowed_read_paths")
    write_roots = permission_roots(project_root, permissions.get("allowed_write_paths", []), "allowed_write_paths")
    forbidden_roots = permission_roots(project_root, permissions.get("forbidden_paths", []), "forbidden_paths")
    if not read_roots or not write_roots:
        raise ToolError("task must authorize read and write roots")
    if not is_within(workdir, write_roots) or is_within(workdir, forbidden_roots):
        raise ToolError("work_directory is not authorized for writes")
    return project_root, workdir, read_roots, write_roots, forbidden_roots


def collect_candidates(task: dict[str, Any], project_root: Path, read_roots: list[Path], forbidden_roots: list[Path]) -> list[dict[str, Any]]:
    records = task.get("current_valid_files")
    if not isinstance(records, list):
        raise ToolError("current_valid_files must be a list")
    selected: list[dict[str, Any]] = []
    for rec in records:
        if not isinstance(rec, dict):
            continue
        role = rec.get("role")
        if not isinstance(role, str) or not role.startswith(CANDIDATE_ROLE_PREFIX):
            continue
        value = rec.get("path")
        if not isinstance(value, str) or not value:
            raise ToolError("source candidate is missing path")
        path = resolve_project_path(project_root, value, "source candidate")
        if not is_within(path, read_roots) or is_within(path, forbidden_roots):
            raise ToolError(f"source candidate is outside authorized read scope: {value}")
        if not path.is_file() or path.is_symlink():
            selected.append({"path": path, "input_record": rec, "valid": False, "reason": "NOT_REGULAR_FILE", "source_label": "UNKNOWN"})
            continue
        valid, reason, label = inspect_signature(path)
        data = path.read_bytes()
        selected.append({
            "path": path,
            "input_record": rec,
            "valid": valid,
            "reason": reason,
            "source_label": label,
            "size_bytes": len(data),
            "modified_at": utc_mtime(path),
            "sha256": sha256_bytes(data),
        })
    if not selected:
        raise ToolError("no bounded source_candidate file records were supplied in current_valid_files")
    return selected


def confirmation(task: dict[str, Any], category: str, question: str, reason: str, options: list[str], affected: list[str]) -> dict[str, Any]:
    digest = hashlib.sha256((task["task_id"] + category + "|".join(options)).encode()).hexdigest()[:12]
    return {
        "schema_version": 2,
        "decision_id": f"dec_{task['task_id']}_{digest}",
        "scope": "WORKSTREAM",
        "workstream_id": task["workstream_id"],
        "source_task_id": task["task_id"],
        "category": category,
        "question": question,
        "reason": reason,
        "affected_records": affected,
        "available_options": options,
        "recommended_option": None,
        "blocking": True,
    }


def component(status: str, summary: str, outcome: str, *, created: list[dict[str, Any]] | None = None, warnings: list[dict[str, Any]] | None = None, failure: dict[str, Any] | None = None, report: str | None = None, log: str | None = None) -> dict[str, Any]:
    return {
        "skill_name": "source_recognition",
        "status": status,
        "summary": summary,
        "outcome_code": outcome,
        "key_findings": [],
        "created_files": created or [],
        "modified_files": [],
        "validated_files": [],
        "warnings": warnings or [],
        "failure": failure,
        "detail_files": {"log_file": log, "report_file": report, "result_data_file": None},
    }


def responsibility(task: dict[str, Any], status: str, summary: str, operation_result: dict[str, Any], *, artifacts: list[dict[str, Any]] | None = None, confirmations: list[dict[str, Any]] | None = None, warnings: list[dict[str, Any]] | None = None, failure: dict[str, Any] | None = None, recommendation: str = "") -> dict[str, Any]:
    return {
        "schema_version": 2,
        "task_id": task["task_id"],
        "workstream_id": task["workstream_id"],
        "task_unit_mode": "OPERATION",
        "status": status,
        "execution_summary": summary,
        "operation_result": operation_result,
        "validation_result": None,
        "artifact_candidates": artifacts or [],
        "confirmation_items": confirmations or [],
        "warnings": warnings or [],
        "failure": failure,
        "next_step_recommendation": recommendation,
    }


def atomic_copy(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{target.name}.", dir=str(target.parent))
    tmp = Path(temp_name)
    try:
        with source.open("rb") as src, os.fdopen(fd, "wb") as dst:
            shutil.copyfileobj(src, dst)
            dst.flush()
            os.fsync(dst.fileno())
        os.replace(tmp, target)
    finally:
        if tmp.exists():
            tmp.unlink()


def write_atomic(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent))
    tmp = Path(temp_name)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def yaml_bytes(obj: Any) -> bytes:
    text = yaml.safe_dump(obj, allow_unicode=True, sort_keys=False, width=1000)
    return (text if text.endswith("\n") else text + "\n").encode("utf-8")


def run(task_path: Path) -> tuple[int, dict[str, Any]]:
    started = time.perf_counter()
    task: dict[str, Any] | None = None
    try:
        check_semantic_source()
        task = load_yaml(task_path)
        project_root, workdir, read_roots, write_roots, forbidden_roots = validate_task(task, task_path)
        ensure_parent_not_symlink(project_root, workdir / "dummy")
        candidates = collect_candidates(task, project_root, read_roots, forbidden_roots)
        valid = [item for item in candidates if item["valid"]]
        report_rel = (workdir / "source_recognition_report.yaml").resolve().relative_to(project_root).as_posix()
        log_rel = (workdir / "source_recognition.log").resolve().relative_to(project_root).as_posix()
        report_path = project_root / report_rel
        log_path = project_root / log_rel
        for path in (report_path, log_path):
            if not is_within(path, write_roots) or is_within(path, forbidden_roots):
                raise ToolError(f"detail output is outside authorized write scope: {path}")
            ensure_parent_not_symlink(project_root, path)

        report_candidates = []
        for item in candidates:
            report_candidates.append({
                "candidate_id": candidate_id(item["path"], item.get("sha256", hashlib.sha256(str(item["path"]).encode()).hexdigest())),
                "path": item["path"].resolve().relative_to(project_root).as_posix(),
                "valid": item["valid"],
                "reason": item["reason"],
                "source_label": item["source_label"],
                "size_bytes": item.get("size_bytes"),
                "modified_at": item.get("modified_at"),
                "sha256": item.get("sha256"),
            })

        if len(valid) == 0:
            report = {"schema_version": 1, "task_id": task["task_id"], "workstream_id": task["workstream_id"], "outcome": "NO_VALID_SOURCE", "candidates": report_candidates, "selected_candidate_id": None, "action": None, "destination_path": None}
            write_atomic(report_path, yaml_bytes(report))
            write_atomic(log_path, f"NO_VALID_SOURCE\telapsed_ms={(time.perf_counter()-started)*1000:.3f}\n".encode())
            op = component("BLOCKED", "No valid supported local structure source was found in the bounded candidate set.", "NO_VALID_SOURCE", report=report_rel, log=log_rel)
            return 0, responsibility(task, "BLOCKED", op["summary"], op, recommendation="Provide one valid local PDB/mmCIF/AF3 CIF source candidate.")

        if len(valid) > 1:
            options = [candidate_id(item["path"], item["sha256"]) for item in valid]
            affected = [item["path"].resolve().relative_to(project_root).as_posix() for item in valid]
            conf = confirmation(task, "SOURCE_SELECTION", "Which valid source structure should be used?", "Multiple valid bounded source candidates are available; deterministic selection is not permitted.", options, affected)
            report = {"schema_version": 1, "task_id": task["task_id"], "workstream_id": task["workstream_id"], "outcome": "SOURCE_SELECTION_REQUIRED", "candidates": report_candidates, "selected_candidate_id": None, "action": None, "destination_path": None}
            write_atomic(report_path, yaml_bytes(report))
            write_atomic(log_path, f"SOURCE_SELECTION_REQUIRED\tcount={len(valid)}\telapsed_ms={(time.perf_counter()-started)*1000:.3f}\n".encode())
            op = component("BLOCKED", "Multiple valid source structures require an explicit selection.", "SOURCE_SELECTION_REQUIRED", report=report_rel, log=log_rel)
            return 0, responsibility(task, "BLOCKED", op["summary"], op, confirmations=[conf], recommendation="Resolve the source selection and create a new narrowed source-recognition task.")

        selected = valid[0]
        source = selected["path"]
        target = workdir / source.name
        ensure_parent_not_symlink(project_root, target)
        if not is_within(target, write_roots) or is_within(target, forbidden_roots):
            raise ToolError("destination is outside authorized write scope")
        source_sha = selected["sha256"]
        action = "COPIED"
        created_by_this_run = False
        if target.exists():
            if target.is_symlink() or not target.is_file():
                raise ToolError("existing destination is not a regular file")
            target_sha = sha256_bytes(target.read_bytes())
            if target_sha == source_sha:
                action = "REUSED_IDENTICAL_COPY"
            else:
                conf = confirmation(task, "SOURCE_DESTINATION_CONFLICT", "How should the existing different destination file be handled?", "The default destination already exists with different bytes; deterministic source recognition never overwrites or auto-renames it.", ["choose_different_destination_policy", "resolve_existing_destination_manually"], [target.resolve().relative_to(project_root).as_posix(), source.resolve().relative_to(project_root).as_posix()])
                report = {"schema_version": 1, "task_id": task["task_id"], "workstream_id": task["workstream_id"], "outcome": "DESTINATION_CONFLICT", "candidates": report_candidates, "selected_candidate_id": candidate_id(source, source_sha), "action": None, "source_path": source.resolve().relative_to(project_root).as_posix(), "source_sha256": source_sha, "destination_path": target.resolve().relative_to(project_root).as_posix(), "destination_sha256": target_sha}
                write_atomic(report_path, yaml_bytes(report))
                write_atomic(log_path, f"DESTINATION_CONFLICT\telapsed_ms={(time.perf_counter()-started)*1000:.3f}\n".encode())
                op = component("BLOCKED", "The default destination conflicts with an existing different file.", "DESTINATION_CONFLICT", report=report_rel, log=log_rel)
                return 0, responsibility(task, "BLOCKED", op["summary"], op, confirmations=[conf], recommendation="Resolve the destination conflict; no overwrite was performed.")
        else:
            atomic_copy(source, target)
            created_by_this_run = True
            target_sha = sha256_bytes(target.read_bytes())
            if target_sha != source_sha:
                try:
                    target.unlink()
                except OSError:
                    pass
                raise ToolError("destination SHA-256 does not match source after copy")

        target_record = file_record(target, project_root, role="selected_source_structure", source_task=task["task_id"])
        report = {
            "schema_version": 1,
            "task_id": task["task_id"],
            "workstream_id": task["workstream_id"],
            "outcome": "SOURCE_SELECTED",
            "candidates": report_candidates,
            "selected_candidate_id": candidate_id(source, source_sha),
            "source_label": selected["source_label"],
            "source_path": source.resolve().relative_to(project_root).as_posix(),
            "source_sha256": source_sha,
            "action": action,
            "destination_path": target_record["path"],
            "destination_sha256": target_record["sha256"],
        }
        try:
            write_atomic(report_path, yaml_bytes(report))
            write_atomic(log_path, f"{action}\tsource={report['source_path']}\tdestination={report['destination_path']}\telapsed_ms={(time.perf_counter()-started)*1000:.3f}\n".encode())
        except Exception:
            if created_by_this_run and target.exists():
                try:
                    target.unlink()
                except OSError:
                    pass
            raise
        op = component("DONE", f"Selected and {action.lower()} one local structure source with matching SHA-256.", "SOURCE_SELECTED", created=[target_record] if created_by_this_run else [], report=report_rel, log=log_rel)
        artifact = {"artifact_type": "STRUCTURE", "files": [target_record], "derived_from_artifact_set_ids": []}
        return 0, responsibility(task, "DONE", op["summary"], op, artifacts=[artifact], recommendation="Continue with component and residue classification.")
    except Exception as exc:
        failure = {"failure_type": "SOURCE_RECOGNITION_TOOL_ERROR", "failure_reason": str(exc), "recoverable": True, "blocked_by": []}
        if task and isinstance(task.get("task_id"), str) and isinstance(task.get("workstream_id"), str):
            op = component("FAILED", "Deterministic source recognition failed before a safe task result could be completed.", "TOOL_ERROR", failure=failure)
            payload = responsibility(task, "FAILED", op["summary"], op, failure=failure, recommendation="Inspect the deterministic Tool error and task permissions before retrying with a new task ID.")
            payload["tool_elapsed_ms"] = round((time.perf_counter() - started) * 1000, 3)
            return 2, payload
        return 2, {"status": "ERROR", "errors": [str(exc)], "tool_version": VERSION, "elapsed_ms": round((time.perf_counter() - started) * 1000, 3)}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Deterministic backend for source_recognition Operation")
    parser.add_argument("--task", required=True)
    parser.add_argument("--output")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    code, payload = run(Path(args.task).resolve())
    text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    print(text, end="")
    if args.output:
        Path(args.output).write_text(text, encoding="utf-8")
    return code


if __name__ == "__main__":
    raise SystemExit(main())
